name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        
    - name: Build with Gradle
      working-directory: wear
      run: |
        export storePassword=${{ secrets.STORE_PASSWORD }}
        export keyAlias=${{ secrets.KEY_ALIAS }}
        export keyPassword=${{ secrets.KEY_PASSWORD }}
        export storeFile=${{ secrets.STORE_FILE }}
        ./../gradlew assembleFullRelease
          
    - name: sign apk
      working-directory: wear
      run: |
        export storePassword=${{ secrets.STORE_PASSWORD }}
        export keyAlias=${{ secrets.KEY_ALIAS }}
        export keyPassword=${{ secrets.KEY_PASSWORD }}
        export storeFile=${{ secrets.STORE_FILE }}
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore $storeFile -storepass $storePassword \
          -keypass $keyPassword build/outputs/apk/full/release/wear-full-release-unsigned.apk $keyAlias

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wear-os-apk
        path: wear/build/outputs/apk/full/release/*.apk
        # app/build/outputs/apk/full/release
